on:
  schedule:
    - cron: '15 11 * * *'
  workflow_dispatch:
  pull_request:
    branches:
      - develop

name: Test Workflow
jobs:
  PR_Decoration:
    name: Test Workflow on branches
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          - ref: develop

      - name: Install Sonarscanner
        run: |
          echo "Installing Sonar scanner for dotnet"
          dotnet tool install --global dotnet-sonarscanner

      - name: Echo Github branch
        run: echo "Branch is $GITHUB_REF"