on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
  pull_request:
    branches:
      - develop

name: Test Workflow with if
jobs:
  PR_Decoration:
    name: Test Workflow on branches with if
    runs-on: macos-latest
    env:
      GITHUBBRANCH: "develop"
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: ${{ env.GITHUBBRANCH }}

      - name: Install Sonarscanner
        run: |
          echo "Installing Sonar scanner for dotnet"
          dotnet tool install --global dotnet-sonarscanner

      - name: Echo Github branch
        run: echo "Branch is $GITHUB_REF"
        
      - name: Echo Github Event name
        run: echo "Event is $GITHUB_EVENT_NAME"
        
      - name: Echo when action is on schedule
        if: ${{ github.event_name == 'schedule' }}
        run: echo "Workflow ran on schedule"
