on:
  - workflow_dispatch
name: Deploy web
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "readme.MD"
          target: "/home/git/"

#       - name: copy source
#         run: |
#           scp ${{ github.workspace }}/ root@www.pascalherms.nl:/home/git/
