on:
  - push
  - pull_request
name: Deploy web
jobs:
  buildbeta:
    name: deploy to Beta server
    if: contains(github.ref,'-beta')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "${{ github.workspace }}/*"
          target: "/home/git/beta"
  buildprod:
    name: deploy to Prod server
    if: contains(github.ref,'main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "${{ github.workspace }}/*"
          target: "/home/git/prod"

#       - name: copy source
#         run: |
#           scp ${{ github.workspace }}/ root@www.pascalherms.nl:/home/git/
